const path = require( 'path' );
const defaultConfig = require('@wordpress/scripts/config/webpack.config');
const RemoveEmptyScriptsPlugin = require( 'webpack-remove-empty-scripts' );

module.exports = {
    ...defaultConfig,
    entry: {
        'js/cs-admin':  path.resolve( process.cwd(), 'resources/js', 'cs-admin.js' ),
        'js/cs-admin-order':  path.resolve( process.cwd(), 'resources/js', 'cs-admin-order.js' ),
        'js/cs-student':  path.resolve( process.cwd(), 'resources/js', 'cs-student.js' ),
        'js/cs-checkout':  path.resolve( process.cwd(), 'resources/js', 'cs-checkout.js' ),
        'js/hystmodal':  path.resolve( process.cwd(), 'resources/js', 'hystmodal.min.js' ),
        // 'js/cs-checkout-groups':  path.resolve( process.cwd(), 'resources/js', 'cs-checkout-groups.js' ),
        'css/cs-frontend': path.resolve( process.cwd(), 'resources/scss', 'cs-frontend.scss' ),
        'css/cs-checkout': path.resolve( process.cwd(), 'resources/scss', 'cs-checkout.scss' ),
        'css/cs-admin': path.resolve( process.cwd(), 'resources/scss', 'cs-admin.scss' ),
        'css/cs-hystmodal': path.resolve( process.cwd(), 'resources/scss', 'cs-hystmodal.scss' ),
    },
    plugins: [
        // Include WP's plugin config.
        ...defaultConfig.plugins,

        // Removes the empty `.js` files generated by webpack but
        // sets it after WP has generated its `*.asset.php` file.
        new RemoveEmptyScriptsPlugin( {
            stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS
        } )
    ],
    externals: {
        react: 'React',
        'react-dom': 'ReactDOM',
    },
};